#-------------------------------------------------
#
# Project created by QtCreator 2016-10-01T08:23:59
#
#-------------------------------------------------

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets network

TARGET = gcom
TEMPLATE = app

LIBS += -L/usr/local/lib \
    -lopencv_core \
    -lopencv_imgproc \
    -lopencv_face \
    -lopencv_objdetect \
    -lopencv_highgui \
    -lopencv_imgcodecs \

SOURCES += main.cpp\
    modules/uas_message/uas_message_tcp_framer.cpp \
    modules/uas_message/request_message.cpp \
    modules/uas_message/system_info_message.cpp \
    modules/uas_message/command_message.cpp \
    modules/uas_message/response_message.cpp \
    gcom_controller.cpp \
    modules/mavlink_relay/mavlink_relay_tcp.cpp \
    modules/uas_dcnc/dcnc.cpp \
    modules/uas_message/image_tagger_message.cpp \
    modules/img_proc/CanadaGoose.cpp \
    modules/imp_API/imp_api.cpp \
    modules/imp_API/goose_data.cpp \
    modules/imp_API/graphicsscene.cpp

HEADERS  += \
    modules/uas_message/uas_message.hpp \
    modules/mavlink_relay/mavlink_relay_tcp.hpp \
    modules/uas_message/request_message.hpp \
    modules/uas_message/system_info_message.hpp \
    modules/uas_message/command_message.hpp \
    modules/uas_message/response_message.hpp \
    gcom_controller.hpp \
    modules/uas_dcnc/dcnc.hpp \
    modules/uas_message/image_tagger_message.hpp \
    modules/img_proc/CanadaGoose.h \
    modules/uas_message/uas_message_tcp_framer.hpp \
    modules/imp_API/imp_api.hpp \
    documentation/latex/ardupilotmega_8h.tex.tmp \
    documentation/man/man3/ardupilotmega.h.3 \
    documentation/man/man3/ASLUAV.h.3 \
    documentation/man/man3/autoquad.h.3 \
    documentation/man/man3/common.h.3 \
    documentation/man/man3/matrixpilot.h.3 \
    documentation/man/man3/mavlink.h.3 \
    documentation/man/man3/mavlink_conversions.h.3 \
    documentation/man/man3/minimal.h.3 \
    documentation/man/man3/slugs.h.3 \
    documentation/man/man3/test.h.3 \
    documentation/man/man3/uAvionix.h.3 \
    Mavlink/ardupilotmega/ardupilotmega.h \
    Mavlink/ardupilotmega/mavlink.h \
    Mavlink/ardupilotmega/mavlink_msg_adap_tuning.h \
    Mavlink/ardupilotmega/mavlink_msg_ahrs.h \
    Mavlink/ardupilotmega/mavlink_msg_ahrs2.h \
    Mavlink/ardupilotmega/mavlink_msg_ahrs3.h \
    Mavlink/ardupilotmega/mavlink_msg_airspeed_autocal.h \
    Mavlink/ardupilotmega/mavlink_msg_ap_adc.h \
    Mavlink/ardupilotmega/mavlink_msg_autopilot_version_request.h \
    Mavlink/ardupilotmega/mavlink_msg_battery2.h \
    Mavlink/ardupilotmega/mavlink_msg_camera_feedback.h \
    Mavlink/ardupilotmega/mavlink_msg_camera_status.h \
    Mavlink/ardupilotmega/mavlink_msg_compassmot_status.h \
    Mavlink/ardupilotmega/mavlink_msg_data16.h \
    Mavlink/ardupilotmega/mavlink_msg_data32.h \
    Mavlink/ardupilotmega/mavlink_msg_data64.h \
    Mavlink/ardupilotmega/mavlink_msg_data96.h \
    Mavlink/ardupilotmega/mavlink_msg_device_op_read.h \
    Mavlink/ardupilotmega/mavlink_msg_device_op_read_reply.h \
    Mavlink/ardupilotmega/mavlink_msg_device_op_write.h \
    Mavlink/ardupilotmega/mavlink_msg_device_op_write_reply.h \
    Mavlink/ardupilotmega/mavlink_msg_digicam_configure.h \
    Mavlink/ardupilotmega/mavlink_msg_digicam_control.h \
    Mavlink/ardupilotmega/mavlink_msg_ekf_status_report.h \
    Mavlink/ardupilotmega/mavlink_msg_fence_fetch_point.h \
    Mavlink/ardupilotmega/mavlink_msg_fence_point.h \
    Mavlink/ardupilotmega/mavlink_msg_fence_status.h \
    Mavlink/ardupilotmega/mavlink_msg_gimbal_control.h \
    Mavlink/ardupilotmega/mavlink_msg_gimbal_report.h \
    Mavlink/ardupilotmega/mavlink_msg_gimbal_torque_cmd_report.h \
    Mavlink/ardupilotmega/mavlink_msg_gopro_get_request.h \
    Mavlink/ardupilotmega/mavlink_msg_gopro_get_response.h \
    Mavlink/ardupilotmega/mavlink_msg_gopro_heartbeat.h \
    Mavlink/ardupilotmega/mavlink_msg_gopro_set_request.h \
    Mavlink/ardupilotmega/mavlink_msg_gopro_set_response.h \
    Mavlink/ardupilotmega/mavlink_msg_hwstatus.h \
    Mavlink/ardupilotmega/mavlink_msg_led_control.h \
    Mavlink/ardupilotmega/mavlink_msg_limits_status.h \
    Mavlink/ardupilotmega/mavlink_msg_mag_cal_progress.h \
    Mavlink/ardupilotmega/mavlink_msg_mag_cal_report.h \
    Mavlink/ardupilotmega/mavlink_msg_meminfo.h \
    Mavlink/ardupilotmega/mavlink_msg_mount_configure.h \
    Mavlink/ardupilotmega/mavlink_msg_mount_control.h \
    Mavlink/ardupilotmega/mavlink_msg_mount_status.h \
    Mavlink/ardupilotmega/mavlink_msg_pid_tuning.h \
    Mavlink/ardupilotmega/mavlink_msg_radio.h \
    Mavlink/ardupilotmega/mavlink_msg_rally_fetch_point.h \
    Mavlink/ardupilotmega/mavlink_msg_rally_point.h \
    Mavlink/ardupilotmega/mavlink_msg_rangefinder.h \
    Mavlink/ardupilotmega/mavlink_msg_remote_log_block_status.h \
    Mavlink/ardupilotmega/mavlink_msg_remote_log_data_block.h \
    Mavlink/ardupilotmega/mavlink_msg_rpm.h \
    Mavlink/ardupilotmega/mavlink_msg_sensor_offsets.h \
    Mavlink/ardupilotmega/mavlink_msg_set_mag_offsets.h \
    Mavlink/ardupilotmega/mavlink_msg_simstate.h \
    Mavlink/ardupilotmega/mavlink_msg_wind.h \
    Mavlink/ardupilotmega/testsuite.h \
    Mavlink/ardupilotmega/version.h \
    Mavlink/ASLUAV/ASLUAV.h \
    Mavlink/ASLUAV/mavlink.h \
    Mavlink/ASLUAV/mavlink_msg_asl_obctrl.h \
    Mavlink/ASLUAV/mavlink_msg_aslctrl_data.h \
    Mavlink/ASLUAV/mavlink_msg_aslctrl_debug.h \
    Mavlink/ASLUAV/mavlink_msg_asluav_status.h \
    Mavlink/ASLUAV/mavlink_msg_ekf_ext.h \
    Mavlink/ASLUAV/mavlink_msg_fw_soaring_data.h \
    Mavlink/ASLUAV/mavlink_msg_sens_atmos.h \
    Mavlink/ASLUAV/mavlink_msg_sens_batmon.h \
    Mavlink/ASLUAV/mavlink_msg_sens_mppt.h \
    Mavlink/ASLUAV/mavlink_msg_sens_power.h \
    Mavlink/ASLUAV/mavlink_msg_sens_power_board.h \
    Mavlink/ASLUAV/mavlink_msg_sensorpod_status.h \
    Mavlink/ASLUAV/testsuite.h \
    Mavlink/ASLUAV/version.h \
    Mavlink/autoquad/autoquad.h \
    Mavlink/autoquad/mavlink.h \
    Mavlink/autoquad/mavlink_msg_aq_esc_telemetry.h \
    Mavlink/autoquad/mavlink_msg_aq_telemetry_f.h \
    Mavlink/autoquad/testsuite.h \
    Mavlink/autoquad/version.h \
    Mavlink/common/common.h \
    Mavlink/common/mavlink.h \
    Mavlink/common/mavlink_msg_actuator_control_target.h \
    Mavlink/common/mavlink_msg_adsb_vehicle.h \
    Mavlink/common/mavlink_msg_altitude.h \
    Mavlink/common/mavlink_msg_att_pos_mocap.h \
    Mavlink/common/mavlink_msg_attitude.h \
    Mavlink/common/mavlink_msg_attitude_quaternion.h \
    Mavlink/common/mavlink_msg_attitude_quaternion_cov.h \
    Mavlink/common/mavlink_msg_attitude_target.h \
    Mavlink/common/mavlink_msg_auth_key.h \
    Mavlink/common/mavlink_msg_autopilot_version.h \
    Mavlink/common/mavlink_msg_battery_status.h \
    Mavlink/common/mavlink_msg_button_change.h \
    Mavlink/common/mavlink_msg_camera_capture_status.h \
    Mavlink/common/mavlink_msg_camera_image_captured.h \
    Mavlink/common/mavlink_msg_camera_information.h \
    Mavlink/common/mavlink_msg_camera_settings.h \
    Mavlink/common/mavlink_msg_camera_trigger.h \
    Mavlink/common/mavlink_msg_change_operator_control.h \
    Mavlink/common/mavlink_msg_change_operator_control_ack.h \
    Mavlink/common/mavlink_msg_collision.h \
    Mavlink/common/mavlink_msg_command_ack.h \
    Mavlink/common/mavlink_msg_command_int.h \
    Mavlink/common/mavlink_msg_command_long.h \
    Mavlink/common/mavlink_msg_control_system_state.h \
    Mavlink/common/mavlink_msg_data_stream.h \
    Mavlink/common/mavlink_msg_data_transmission_handshake.h \
    Mavlink/common/mavlink_msg_debug.h \
    Mavlink/common/mavlink_msg_debug_vect.h \
    Mavlink/common/mavlink_msg_distance_sensor.h \
    Mavlink/common/mavlink_msg_encapsulated_data.h \
    Mavlink/common/mavlink_msg_estimator_status.h \
    Mavlink/common/mavlink_msg_extended_sys_state.h \
    Mavlink/common/mavlink_msg_file_transfer_protocol.h \
    Mavlink/common/mavlink_msg_flight_information.h \
    Mavlink/common/mavlink_msg_follow_target.h \
    Mavlink/common/mavlink_msg_global_position_int.h \
    Mavlink/common/mavlink_msg_global_position_int_cov.h \
    Mavlink/common/mavlink_msg_global_vision_position_estimate.h \
    Mavlink/common/mavlink_msg_gps2_raw.h \
    Mavlink/common/mavlink_msg_gps2_rtk.h \
    Mavlink/common/mavlink_msg_gps_global_origin.h \
    Mavlink/common/mavlink_msg_gps_inject_data.h \
    Mavlink/common/mavlink_msg_gps_input.h \
    Mavlink/common/mavlink_msg_gps_raw_int.h \
    Mavlink/common/mavlink_msg_gps_rtcm_data.h \
    Mavlink/common/mavlink_msg_gps_rtk.h \
    Mavlink/common/mavlink_msg_gps_status.h \
    Mavlink/common/mavlink_msg_heartbeat.h \
    Mavlink/common/mavlink_msg_high_latency.h \
    Mavlink/common/mavlink_msg_highres_imu.h \
    Mavlink/common/mavlink_msg_hil_actuator_controls.h \
    Mavlink/common/mavlink_msg_hil_controls.h \
    Mavlink/common/mavlink_msg_hil_gps.h \
    Mavlink/common/mavlink_msg_hil_optical_flow.h \
    Mavlink/common/mavlink_msg_hil_rc_inputs_raw.h \
    Mavlink/common/mavlink_msg_hil_sensor.h \
    Mavlink/common/mavlink_msg_hil_state.h \
    Mavlink/common/mavlink_msg_hil_state_quaternion.h \
    Mavlink/common/mavlink_msg_home_position.h \
    Mavlink/common/mavlink_msg_landing_target.h \
    Mavlink/common/mavlink_msg_local_position_ned.h \
    Mavlink/common/mavlink_msg_local_position_ned_cov.h \
    Mavlink/common/mavlink_msg_local_position_ned_system_global_offset.h \
    Mavlink/common/mavlink_msg_log_data.h \
    Mavlink/common/mavlink_msg_log_entry.h \
    Mavlink/common/mavlink_msg_log_erase.h \
    Mavlink/common/mavlink_msg_log_request_data.h \
    Mavlink/common/mavlink_msg_log_request_end.h \
    Mavlink/common/mavlink_msg_log_request_list.h \
    Mavlink/common/mavlink_msg_logging_ack.h \
    Mavlink/common/mavlink_msg_logging_data.h \
    Mavlink/common/mavlink_msg_logging_data_acked.h \
    Mavlink/common/mavlink_msg_manual_control.h \
    Mavlink/common/mavlink_msg_manual_setpoint.h \
    Mavlink/common/mavlink_msg_memory_vect.h \
    Mavlink/common/mavlink_msg_message_interval.h \
    Mavlink/common/mavlink_msg_mission_ack.h \
    Mavlink/common/mavlink_msg_mission_clear_all.h \
    Mavlink/common/mavlink_msg_mission_count.h \
    Mavlink/common/mavlink_msg_mission_current.h \
    Mavlink/common/mavlink_msg_mission_item.h \
    Mavlink/common/mavlink_msg_mission_item_int.h \
    Mavlink/common/mavlink_msg_mission_item_reached.h \
    Mavlink/common/mavlink_msg_mission_request.h \
    Mavlink/common/mavlink_msg_mission_request_int.h \
    Mavlink/common/mavlink_msg_mission_request_list.h \
    Mavlink/common/mavlink_msg_mission_request_partial_list.h \
    Mavlink/common/mavlink_msg_mission_set_current.h \
    Mavlink/common/mavlink_msg_mission_write_partial_list.h \
    Mavlink/common/mavlink_msg_mount_orientation.h \
    Mavlink/common/mavlink_msg_named_value_float.h \
    Mavlink/common/mavlink_msg_named_value_int.h \
    Mavlink/common/mavlink_msg_nav_controller_output.h \
    Mavlink/common/mavlink_msg_optical_flow.h \
    Mavlink/common/mavlink_msg_optical_flow_rad.h \
    Mavlink/common/mavlink_msg_param_map_rc.h \
    Mavlink/common/mavlink_msg_param_request_list.h \
    Mavlink/common/mavlink_msg_param_request_read.h \
    Mavlink/common/mavlink_msg_param_set.h \
    Mavlink/common/mavlink_msg_param_value.h \
    Mavlink/common/mavlink_msg_ping.h \
    Mavlink/common/mavlink_msg_play_tune.h \
    Mavlink/common/mavlink_msg_position_target_global_int.h \
    Mavlink/common/mavlink_msg_position_target_local_ned.h \
    Mavlink/common/mavlink_msg_power_status.h \
    Mavlink/common/mavlink_msg_radio_status.h \
    Mavlink/common/mavlink_msg_raw_imu.h \
    Mavlink/common/mavlink_msg_raw_pressure.h \
    Mavlink/common/mavlink_msg_rc_channels.h \
    Mavlink/common/mavlink_msg_rc_channels_override.h \
    Mavlink/common/mavlink_msg_rc_channels_raw.h \
    Mavlink/common/mavlink_msg_rc_channels_scaled.h \
    Mavlink/common/mavlink_msg_request_data_stream.h \
    Mavlink/common/mavlink_msg_resource_request.h \
    Mavlink/common/mavlink_msg_safety_allowed_area.h \
    Mavlink/common/mavlink_msg_safety_set_allowed_area.h \
    Mavlink/common/mavlink_msg_scaled_imu.h \
    Mavlink/common/mavlink_msg_scaled_imu2.h \
    Mavlink/common/mavlink_msg_scaled_imu3.h \
    Mavlink/common/mavlink_msg_scaled_pressure.h \
    Mavlink/common/mavlink_msg_scaled_pressure2.h \
    Mavlink/common/mavlink_msg_scaled_pressure3.h \
    Mavlink/common/mavlink_msg_serial_control.h \
    Mavlink/common/mavlink_msg_servo_output_raw.h \
    Mavlink/common/mavlink_msg_set_actuator_control_target.h \
    Mavlink/common/mavlink_msg_set_attitude_target.h \
    Mavlink/common/mavlink_msg_set_gps_global_origin.h \
    Mavlink/common/mavlink_msg_set_home_position.h \
    Mavlink/common/mavlink_msg_set_mode.h \
    Mavlink/common/mavlink_msg_set_position_target_global_int.h \
    Mavlink/common/mavlink_msg_set_position_target_local_ned.h \
    Mavlink/common/mavlink_msg_setup_signing.h \
    Mavlink/common/mavlink_msg_sim_state.h \
    Mavlink/common/mavlink_msg_statustext.h \
    Mavlink/common/mavlink_msg_storage_information.h \
    Mavlink/common/mavlink_msg_sys_status.h \
    Mavlink/common/mavlink_msg_system_time.h \
    Mavlink/common/mavlink_msg_terrain_check.h \
    Mavlink/common/mavlink_msg_terrain_data.h \
    Mavlink/common/mavlink_msg_terrain_report.h \
    Mavlink/common/mavlink_msg_terrain_request.h \
    Mavlink/common/mavlink_msg_timesync.h \
    Mavlink/common/mavlink_msg_v2_extension.h \
    Mavlink/common/mavlink_msg_vfr_hud.h \
    Mavlink/common/mavlink_msg_vibration.h \
    Mavlink/common/mavlink_msg_vicon_position_estimate.h \
    Mavlink/common/mavlink_msg_vision_position_estimate.h \
    Mavlink/common/mavlink_msg_vision_speed_estimate.h \
    Mavlink/common/mavlink_msg_wind_cov.h \
    Mavlink/common/testsuite.h \
    Mavlink/common/version.h \
    Mavlink/matrixpilot/matrixpilot.h \
    Mavlink/matrixpilot/mavlink.h \
    Mavlink/matrixpilot/mavlink_msg_airspeeds.h \
    Mavlink/matrixpilot/mavlink_msg_altitudes.h \
    Mavlink/matrixpilot/mavlink_msg_flexifunction_buffer_function.h \
    Mavlink/matrixpilot/mavlink_msg_flexifunction_buffer_function_ack.h \
    Mavlink/matrixpilot/mavlink_msg_flexifunction_command.h \
    Mavlink/matrixpilot/mavlink_msg_flexifunction_command_ack.h \
    Mavlink/matrixpilot/mavlink_msg_flexifunction_directory.h \
    Mavlink/matrixpilot/mavlink_msg_flexifunction_directory_ack.h \
    Mavlink/matrixpilot/mavlink_msg_flexifunction_read_req.h \
    Mavlink/matrixpilot/mavlink_msg_flexifunction_set.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f13.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f14.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f15.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f16.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f17.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f18.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f19.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f20.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f21.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f22.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f2_a.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f2_b.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f4.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f5.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f6.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f7.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f8.h \
    Mavlink/matrixpilot/testsuite.h \
    Mavlink/matrixpilot/version.h \
    Mavlink/minimal/mavlink.h \
    Mavlink/minimal/mavlink_msg_heartbeat.h \
    Mavlink/minimal/minimal.h \
    Mavlink/minimal/testsuite.h \
    Mavlink/minimal/version.h \
    Mavlink/slugs/mavlink.h \
    Mavlink/slugs/mavlink_msg_boot.h \
    Mavlink/slugs/mavlink_msg_control_surface.h \
    Mavlink/slugs/mavlink_msg_cpu_load.h \
    Mavlink/slugs/mavlink_msg_ctrl_srfc_pt.h \
    Mavlink/slugs/mavlink_msg_data_log.h \
    Mavlink/slugs/mavlink_msg_diagnostic.h \
    Mavlink/slugs/mavlink_msg_gps_date_time.h \
    Mavlink/slugs/mavlink_msg_isr_location.h \
    Mavlink/slugs/mavlink_msg_mid_lvl_cmds.h \
    Mavlink/slugs/mavlink_msg_novatel_diag.h \
    Mavlink/slugs/mavlink_msg_ptz_status.h \
    Mavlink/slugs/mavlink_msg_sensor_bias.h \
    Mavlink/slugs/mavlink_msg_sensor_diag.h \
    Mavlink/slugs/mavlink_msg_slugs_camera_order.h \
    Mavlink/slugs/mavlink_msg_slugs_configuration_camera.h \
    Mavlink/slugs/mavlink_msg_slugs_mobile_location.h \
    Mavlink/slugs/mavlink_msg_slugs_navigation.h \
    Mavlink/slugs/mavlink_msg_status_gps.h \
    Mavlink/slugs/mavlink_msg_uav_status.h \
    Mavlink/slugs/mavlink_msg_volt_sensor.h \
    Mavlink/slugs/slugs.h \
    Mavlink/slugs/testsuite.h \
    Mavlink/slugs/version.h \
    Mavlink/standard/mavlink.h \
    Mavlink/standard/standard.h \
    Mavlink/standard/testsuite.h \
    Mavlink/standard/version.h \
    Mavlink/test/mavlink.h \
    Mavlink/test/mavlink_msg_test_types.h \
    Mavlink/test/test.h \
    Mavlink/test/testsuite.h \
    Mavlink/test/version.h \
    Mavlink/uAvionix/mavlink.h \
    Mavlink/uAvionix/mavlink_msg_uavionix_adsb_out_cfg.h \
    Mavlink/uAvionix/mavlink_msg_uavionix_adsb_out_dynamic.h \
    Mavlink/uAvionix/mavlink_msg_uavionix_adsb_transceiver_health_report.h \
    Mavlink/uAvionix/testsuite.h \
    Mavlink/uAvionix/uAvionix.h \
    Mavlink/uAvionix/version.h \
    Mavlink/checksum.h \
    Mavlink/mavlink_conversions.h \
    Mavlink/mavlink_get_info.h \
    Mavlink/mavlink_helpers.h \
    Mavlink/mavlink_sha256.h \
    Mavlink/mavlink_types.h \
    Mavlink/protocol.h \
    modules/imp_API/goose_data.hpp \
    modules/imp_API/graphicsscene.h

FORMS    += gcomcontroller.ui

INCLUDEPATH += Mavlink

CONFIG += c++14

RESOURCES = resources.qrc

DESTDIR = $$PWD
DISTFILES += \
    assets/Samples/IMG_0123.jpg \
    assets/Samples.bk/31.jpg \
    assets/impData.txt \
    documentation/html/search/all_0.js \
    documentation/html/search/all_1.js \
    documentation/html/search/all_2.js \
    documentation/html/search/all_3.js \
    documentation/html/search/all_4.js \
    documentation/html/search/all_5.js \
    documentation/html/search/all_6.js \
    documentation/html/search/all_7.js \
    documentation/html/search/all_8.js \
    documentation/html/search/all_9.js \
    documentation/html/search/all_a.js \
    documentation/html/search/all_b.js \
    documentation/html/search/all_c.js \
    documentation/html/search/classes_0.js \
    documentation/html/search/classes_1.js \
    documentation/html/search/classes_2.js \
    documentation/html/search/classes_3.js \
    documentation/html/search/defines_0.js \
    documentation/html/search/files_0.js \
    documentation/html/search/files_1.js \
    documentation/html/search/files_2.js \
    documentation/html/search/files_3.js \
    documentation/html/search/files_4.js \
    documentation/html/search/files_5.js \
    documentation/html/search/files_6.js \
    documentation/html/search/functions_0.js \
    documentation/html/search/pages_0.js \
    documentation/html/search/search.js \
    documentation/html/search/searchdata.js \
    documentation/html/search/variables_0.js \
    documentation/html/search/variables_1.js \
    documentation/html/search/variables_2.js \
    documentation/html/search/variables_3.js \
    documentation/html/search/variables_4.js \
    documentation/html/search/variables_5.js \
    documentation/html/_a_s_l_u_a_v_2mavlink_8h.js \
    documentation/html/_a_s_l_u_a_v_2testsuite_8h.js \
    documentation/html/_a_s_l_u_a_v_2version_8h.js \
    documentation/html/_a_s_l_u_a_v_8h.js \
    documentation/html/annotated_dup.js \
    documentation/html/ardupilotmega_2mavlink_8h.js \
    documentation/html/ardupilotmega_2testsuite_8h.js \
    documentation/html/ardupilotmega_2version_8h.js \
    documentation/html/ardupilotmega_8h.js \
    documentation/html/autoquad_2mavlink_8h.js \
    documentation/html/autoquad_2testsuite_8h.js \
    documentation/html/autoquad_2version_8h.js \
    documentation/html/autoquad_8h.js \
    documentation/html/class_gcom_controller.js \
    documentation/html/common_2mavlink_8h.js \
    documentation/html/common_2testsuite_8h.js \
    documentation/html/common_2version_8h.js \
    documentation/html/common_8h.js \
    documentation/html/dir_006c5adde132422c936285061c441fd6.js \
    documentation/html/dir_0da6529a5eada8fcebcd8e4c2a5a9bb4.js \
    documentation/html/dir_2c8fe6371a64182b88962612e2d59269.js \
    documentation/html/dir_4c057851c48f94592cfeafad14b1565d.js \
    documentation/html/dir_547b956d4166df78c42c5049894a4888.js \
    documentation/html/dir_6439a1e482aa07981dd6ab8c460c3ef8.js \
    documentation/html/dir_64e73385a8b7738563c26ce10415b58d.js \
    documentation/html/dir_83fc68f116d5d7b432bced6cbed0192e.js \
    documentation/html/dir_bcd2bb1aa02f875b186a4aa98bbb035f.js \
    documentation/html/dir_c1a4da077515c6906d4cf31a479036ae.js \
    documentation/html/dir_f2ea229d8e28506b03313778d82f530e.js \
    documentation/html/dynsections.js \
    documentation/html/files.js \
    documentation/html/hierarchy.js \
    documentation/html/jquery.js \
    documentation/html/matrixpilot_2mavlink_8h.js \
    documentation/html/matrixpilot_2testsuite_8h.js \
    documentation/html/matrixpilot_2version_8h.js \
    documentation/html/matrixpilot_8h.js \
    documentation/html/mavlink__conversions_8h.js \
    documentation/html/menu.js \
    documentation/html/menudata.js \
    documentation/html/minimal_2mavlink_8h.js \
    documentation/html/minimal_2testsuite_8h.js \
    documentation/html/minimal_2version_8h.js \
    documentation/html/minimal_8h.js \
    documentation/html/navtree.js \
    documentation/html/navtreedata.js \
    documentation/html/navtreeindex0.js \
    documentation/html/navtreeindex1.js \
    documentation/html/navtreeindex10.js \
    documentation/html/navtreeindex11.js \
    documentation/html/navtreeindex12.js \
    documentation/html/navtreeindex13.js \
    documentation/html/navtreeindex14.js \
    documentation/html/navtreeindex15.js \
    documentation/html/navtreeindex16.js \
    documentation/html/navtreeindex17.js \
    documentation/html/navtreeindex18.js \
    documentation/html/navtreeindex19.js \
    documentation/html/navtreeindex2.js \
    documentation/html/navtreeindex20.js \
    documentation/html/navtreeindex21.js \
    documentation/html/navtreeindex22.js \
    documentation/html/navtreeindex3.js \
    documentation/html/navtreeindex4.js \
    documentation/html/navtreeindex5.js \
    documentation/html/navtreeindex6.js \
    documentation/html/navtreeindex7.js \
    documentation/html/navtreeindex8.js \
    documentation/html/navtreeindex9.js \
    documentation/html/resize.js \
    documentation/html/slugs_2mavlink_8h.js \
    documentation/html/slugs_2testsuite_8h.js \
    documentation/html/slugs_2version_8h.js \
    documentation/html/slugs_8h.js \
    documentation/html/struct____mavlink__field__info.js \
    documentation/html/struct____mavlink__message__info.js \
    documentation/html/struct____mavlink__msg__entry.js \
    documentation/html/struct____mavlink__signing.js \
    documentation/html/struct____mavlink__signing__streams.js \
    documentation/html/struct____mavlink__signing__streams_1_1____mavlink__signing__stream.js \
    documentation/html/struct____mavlink__status.js \
    documentation/html/structmavlink__sha256__ctx.js \
    documentation/html/test_2mavlink_8h.js \
    documentation/html/test_2testsuite_8h.js \
    documentation/html/test_2version_8h.js \
    documentation/html/test_8h.js \
    documentation/html/u_avionix_2mavlink_8h.js \
    documentation/html/u_avionix_2testsuite_8h.js \
    documentation/html/u_avionix_2version_8h.js \
    documentation/html/u_avionix_8h.js \
    documentation/html/union____mavlink__bitfield.js \
    gcom \
    assets/cascades/cascade_for_0.xml \
    assets/cascades/cascade_for_1_.xml \
    assets/cascades/cascade_for_2.xml \
    assets/cascades/cascade_for_2_v2.xml \
    assets/cascades/haarcascade_frontalface_default.xml \
    assets/cascades/new_cascade_for_1_v1.xml \
    assets/gcom_qt_style.xml \
    Mavlink/message_definitions/ardupilotmega.xml \
    Mavlink/message_definitions/ASLUAV.xml \
    Mavlink/message_definitions/autoquad.xml \
    Mavlink/message_definitions/common.xml \
    Mavlink/message_definitions/matrixpilot.xml \
    Mavlink/message_definitions/minimal.xml \
    Mavlink/message_definitions/paparazzi.xml \
    Mavlink/message_definitions/python_array_test.xml \
    Mavlink/message_definitions/slugs.xml \
    Mavlink/message_definitions/standard.xml \
    Mavlink/message_definitions/test.xml \
    Mavlink/message_definitions/ualberta.xml \
    Mavlink/message_definitions/uAvionix.xml \
    assets/Samples/29.jpg \
    assets/Samples.bk/1.jpg \
    assets/Samples.bk/25.jpg \
    assets/Samples.bk/28.jpg \
    assets/Samples.bk/29.jpg \
    assets/Samples.bk/IMG_0123.jpg \
    assets/Samples.bk/IMG_0139.jpg \
    assets/gcom_logo.png \
    documentation/html/search/close.png \
    documentation/html/search/mag_sel.png \
    documentation/html/search/search_l.png \
    documentation/html/search/search_m.png \
    documentation/html/search/search_r.png \
    documentation/html/bc_s.png \
    documentation/html/bdwn.png \
    documentation/html/closed.png \
    documentation/html/doc.png \
    documentation/html/doxygen.png \
    documentation/html/folderclosed.png \
    documentation/html/folderopen.png \
    documentation/html/gcom_logo.png \
    documentation/html/nav_f.png \
    documentation/html/nav_g.png \
    documentation/html/nav_h.png \
    documentation/html/open.png \
    documentation/html/splitbar.png \
    documentation/html/sync_off.png \
    documentation/html/sync_on.png \
    documentation/html/tab_a.png \
    documentation/html/tab_b.png \
    documentation/html/tab_h.png \
    documentation/html/tab_s.png \
    documentation/latex/gcom_logo.png \
    documentation/html/search/search.css \
    documentation/html/doxygen.css \
    documentation/html/navtree.css \
    documentation/html/tabs.css \
    documentation/html/search/all_0.html \
    documentation/html/search/all_1.html \
    documentation/html/search/all_2.html \
    documentation/html/search/all_3.html \
    documentation/html/search/all_4.html \
    documentation/html/search/all_5.html \
    documentation/html/search/all_6.html \
    documentation/html/search/all_7.html \
    documentation/html/search/all_8.html \
    documentation/html/search/all_9.html \
    documentation/html/search/all_a.html \
    documentation/html/search/all_b.html \
    documentation/html/search/all_c.html \
    documentation/html/search/classes_0.html \
    documentation/html/search/classes_1.html \
    documentation/html/search/classes_2.html \
    documentation/html/search/classes_3.html \
    documentation/html/search/defines_0.html \
    documentation/html/search/files_0.html \
    documentation/html/search/files_1.html \
    documentation/html/search/files_2.html \
    documentation/html/search/files_3.html \
    documentation/html/search/files_4.html \
    documentation/html/search/files_5.html \
    documentation/html/search/files_6.html \
    documentation/html/search/functions_0.html \
    documentation/html/search/nomatches.html \
    documentation/html/search/pages_0.html \
    documentation/html/search/variables_0.html \
    documentation/html/search/variables_1.html \
    documentation/html/search/variables_2.html \
    documentation/html/search/variables_3.html \
    documentation/html/search/variables_4.html \
    documentation/html/search/variables_5.html \
    documentation/html/_a_s_l_u_a_v_2mavlink_8h.html \
    documentation/html/_a_s_l_u_a_v_2mavlink_8h_source.html \
    documentation/html/_a_s_l_u_a_v_2testsuite_8h.html \
    documentation/html/_a_s_l_u_a_v_2testsuite_8h_source.html \
    documentation/html/_a_s_l_u_a_v_2version_8h.html \
    documentation/html/_a_s_l_u_a_v_2version_8h_source.html \
    documentation/html/_a_s_l_u_a_v_8h.html \
    documentation/html/_a_s_l_u_a_v_8h_source.html \
    documentation/html/_r_e_a_d_m_e_8md_source.html \
    documentation/html/annotated.html \
    documentation/html/ardupilotmega_2mavlink_8h.html \
    documentation/html/ardupilotmega_2mavlink_8h_source.html \
    documentation/html/ardupilotmega_2testsuite_8h.html \
    documentation/html/ardupilotmega_2testsuite_8h_source.html \
    documentation/html/ardupilotmega_2version_8h.html \
    documentation/html/ardupilotmega_2version_8h_source.html \
    documentation/html/ardupilotmega_8h.html \
    documentation/html/ardupilotmega_8h_source.html \
    documentation/html/autoquad_2mavlink_8h.html \
    documentation/html/autoquad_2mavlink_8h_source.html \
    documentation/html/autoquad_2testsuite_8h.html \
    documentation/html/autoquad_2testsuite_8h_source.html \
    documentation/html/autoquad_2version_8h.html \
    documentation/html/autoquad_2version_8h_source.html \
    documentation/html/autoquad_8h.html \
    documentation/html/autoquad_8h_source.html \
    documentation/html/checksum_8h_source.html \
    documentation/html/class_gcom_controller-members.html \
    documentation/html/class_gcom_controller.html \
    documentation/html/class_u_a_s_message_1_1_u_a_s_message-members.html \
    documentation/html/class_u_a_s_message_1_1_u_a_s_message.html \
    documentation/html/classes.html \
    documentation/html/common_2mavlink_8h.html \
    documentation/html/common_2mavlink_8h_source.html \
    documentation/html/common_2mavlink__msg__heartbeat_8h_source.html \
    documentation/html/common_2testsuite_8h.html \
    documentation/html/common_2testsuite_8h_source.html \
    documentation/html/common_2version_8h.html \
    documentation/html/common_2version_8h_source.html \
    documentation/html/common_8h.html \
    documentation/html/common_8h_source.html \
    documentation/html/dir_000001_000004.html \
    documentation/html/dir_000001_000009.html \
    documentation/html/dir_000002_000004.html \
    documentation/html/dir_000003_000004.html \
    documentation/html/dir_000005_000004.html \
    documentation/html/dir_000007_000004.html \
    documentation/html/dir_006c5adde132422c936285061c441fd6.html \
    documentation/html/dir_0da6529a5eada8fcebcd8e4c2a5a9bb4.html \
    documentation/html/dir_2c8fe6371a64182b88962612e2d59269.html \
    documentation/html/dir_4c057851c48f94592cfeafad14b1565d.html \
    documentation/html/dir_547b956d4166df78c42c5049894a4888.html \
    documentation/html/dir_6439a1e482aa07981dd6ab8c460c3ef8.html \
    documentation/html/dir_64e73385a8b7738563c26ce10415b58d.html \
    documentation/html/dir_83fc68f116d5d7b432bced6cbed0192e.html \
    documentation/html/dir_bcd2bb1aa02f875b186a4aa98bbb035f.html \
    documentation/html/dir_c1a4da077515c6906d4cf31a479036ae.html \
    documentation/html/dir_f2ea229d8e28506b03313778d82f530e.html \
    documentation/html/files.html \
    documentation/html/functions.html \
    documentation/html/functions_vars.html \
    documentation/html/gcomcontroller_8cpp_source.html \
    documentation/html/gcomcontroller_8hpp_source.html \
    documentation/html/globals.html \
    documentation/html/globals_defs.html \
    documentation/html/globals_func.html \
    documentation/html/graph_legend.html \
    documentation/html/hierarchy.html \
    documentation/html/index.html \
    documentation/html/inherits.html \
    documentation/html/main_8cpp_source.html \
    documentation/html/matrixpilot_2mavlink_8h.html \
    documentation/html/matrixpilot_2mavlink_8h_source.html \
    documentation/html/matrixpilot_2testsuite_8h.html \
    documentation/html/matrixpilot_2testsuite_8h_source.html \
    documentation/html/matrixpilot_2version_8h.html \
    documentation/html/matrixpilot_2version_8h_source.html \
    documentation/html/matrixpilot_8h.html \
    documentation/html/matrixpilot_8h_source.html \
    documentation/html/mavlink__conversions_8h.html \
    documentation/html/mavlink__conversions_8h_source.html \
    documentation/html/mavlink__get__info_8h_source.html \
    documentation/html/mavlink__helpers_8h_source.html \
    documentation/html/mavlink__msg__actuator__control__target_8h_source.html \
    documentation/html/mavlink__msg__adsb__vehicle_8h_source.html \
    documentation/html/mavlink__msg__ahrs2_8h_source.html \
    documentation/html/mavlink__msg__ahrs3_8h_source.html \
    documentation/html/mavlink__msg__ahrs_8h_source.html \
    documentation/html/mavlink__msg__airspeed__autocal_8h_source.html \
    documentation/html/mavlink__msg__airspeeds_8h_source.html \
    documentation/html/mavlink__msg__altitude_8h_source.html \
    documentation/html/mavlink__msg__altitudes_8h_source.html \
    documentation/html/mavlink__msg__ap__adc_8h_source.html \
    documentation/html/mavlink__msg__aq__esc__telemetry_8h_source.html \
    documentation/html/mavlink__msg__aq__telemetry__f_8h_source.html \
    documentation/html/mavlink__msg__asl__obctrl_8h_source.html \
    documentation/html/mavlink__msg__aslctrl__data_8h_source.html \
    documentation/html/mavlink__msg__aslctrl__debug_8h_source.html \
    documentation/html/mavlink__msg__asluav__status_8h_source.html \
    documentation/html/mavlink__msg__att__pos__mocap_8h_source.html \
    documentation/html/mavlink__msg__attitude_8h_source.html \
    documentation/html/mavlink__msg__attitude__quaternion_8h_source.html \
    documentation/html/mavlink__msg__attitude__quaternion__cov_8h_source.html \
    documentation/html/mavlink__msg__attitude__target_8h_source.html \
    documentation/html/mavlink__msg__auth__key_8h_source.html \
    documentation/html/mavlink__msg__autopilot__version_8h_source.html \
    documentation/html/mavlink__msg__autopilot__version__request_8h_source.html \
    documentation/html/mavlink__msg__battery2_8h_source.html \
    documentation/html/mavlink__msg__battery__status_8h_source.html \
    documentation/html/mavlink__msg__boot_8h_source.html \
    documentation/html/mavlink__msg__button__change_8h_source.html \
    documentation/html/mavlink__msg__camera__feedback_8h_source.html \
    documentation/html/mavlink__msg__camera__status_8h_source.html \
    documentation/html/mavlink__msg__camera__trigger_8h_source.html \
    documentation/html/mavlink__msg__change__operator__control_8h_source.html \
    documentation/html/mavlink__msg__change__operator__control__ack_8h_source.html \
    documentation/html/mavlink__msg__collision_8h_source.html \
    documentation/html/mavlink__msg__command__ack_8h_source.html \
    documentation/html/mavlink__msg__command__int_8h_source.html \
    documentation/html/mavlink__msg__command__long_8h_source.html \
    documentation/html/mavlink__msg__compassmot__status_8h_source.html \
    documentation/html/mavlink__msg__control__surface_8h_source.html \
    documentation/html/mavlink__msg__control__system__state_8h_source.html \
    documentation/html/mavlink__msg__cpu__load_8h_source.html \
    documentation/html/mavlink__msg__ctrl__srfc__pt_8h_source.html \
    documentation/html/mavlink__msg__data16_8h_source.html \
    documentation/html/mavlink__msg__data32_8h_source.html \
    documentation/html/mavlink__msg__data64_8h_source.html \
    documentation/html/mavlink__msg__data96_8h_source.html \
    documentation/html/mavlink__msg__data__log_8h_source.html \
    documentation/html/mavlink__msg__data__stream_8h_source.html \
    documentation/html/mavlink__msg__data__transmission__handshake_8h_source.html \
    documentation/html/mavlink__msg__debug_8h_source.html \
    documentation/html/mavlink__msg__debug__vect_8h_source.html \
    documentation/html/mavlink__msg__diagnostic_8h_source.html \
    documentation/html/mavlink__msg__digicam__configure_8h_source.html \
    documentation/html/mavlink__msg__digicam__control_8h_source.html \
    documentation/html/mavlink__msg__distance__sensor_8h_source.html \
    documentation/html/mavlink__msg__ekf__ext_8h_source.html \
    documentation/html/mavlink__msg__ekf__status__report_8h_source.html \
    documentation/html/mavlink__msg__encapsulated__data_8h_source.html \
    documentation/html/mavlink__msg__estimator__status_8h_source.html \
    documentation/html/mavlink__msg__extended__sys__state_8h_source.html \
    documentation/html/mavlink__msg__fence__fetch__point_8h_source.html \
    documentation/html/mavlink__msg__fence__point_8h_source.html \
    documentation/html/mavlink__msg__fence__status_8h_source.html \
    documentation/html/mavlink__msg__file__transfer__protocol_8h_source.html \
    documentation/html/mavlink__msg__flexifunction__buffer__function_8h_source.html \
    documentation/html/mavlink__msg__flexifunction__buffer__function__ack_8h_source.html \
    documentation/html/mavlink__msg__flexifunction__command_8h_source.html \
    documentation/html/mavlink__msg__flexifunction__command__ack_8h_source.html \
    documentation/html/mavlink__msg__flexifunction__directory_8h_source.html \
    documentation/html/mavlink__msg__flexifunction__directory__ack_8h_source.html \
    documentation/html/mavlink__msg__flexifunction__read__req_8h_source.html \
    documentation/html/mavlink__msg__flexifunction__set_8h_source.html \
    documentation/html/mavlink__msg__follow__target_8h_source.html \
    documentation/html/mavlink__msg__fw__soaring__data_8h_source.html \
    documentation/html/mavlink__msg__gimbal__control_8h_source.html \
    documentation/html/mavlink__msg__gimbal__report_8h_source.html \
    documentation/html/mavlink__msg__gimbal__torque__cmd__report_8h_source.html \
    documentation/html/mavlink__msg__global__position__int_8h_source.html \
    documentation/html/mavlink__msg__global__position__int__cov_8h_source.html \
    documentation/html/mavlink__msg__global__vision__position__estimate_8h_source.html \
    documentation/html/mavlink__msg__gopro__get__request_8h_source.html \
    documentation/html/mavlink__msg__gopro__get__response_8h_source.html \
    documentation/html/mavlink__msg__gopro__heartbeat_8h_source.html \
    documentation/html/mavlink__msg__gopro__set__request_8h_source.html \
    documentation/html/mavlink__msg__gopro__set__response_8h_source.html \
    documentation/html/mavlink__msg__gps2__raw_8h_source.html \
    documentation/html/mavlink__msg__gps2__rtk_8h_source.html \
    documentation/html/mavlink__msg__gps__date__time_8h_source.html \
    documentation/html/mavlink__msg__gps__global__origin_8h_source.html \
    documentation/html/mavlink__msg__gps__inject__data_8h_source.html \
    documentation/html/mavlink__msg__gps__input_8h_source.html \
    documentation/html/mavlink__msg__gps__raw__int_8h_source.html \
    documentation/html/mavlink__msg__gps__rtcm__data_8h_source.html \
    documentation/html/mavlink__msg__gps__rtk_8h_source.html \
    documentation/html/mavlink__msg__gps__status_8h_source.html \
    documentation/html/mavlink__msg__highres__imu_8h_source.html \
    documentation/html/mavlink__msg__hil__actuator__controls_8h_source.html \
    documentation/html/mavlink__msg__hil__controls_8h_source.html \
    documentation/html/mavlink__msg__hil__gps_8h_source.html \
    documentation/html/mavlink__msg__hil__optical__flow_8h_source.html \
    documentation/html/mavlink__msg__hil__rc__inputs__raw_8h_source.html \
    documentation/html/mavlink__msg__hil__sensor_8h_source.html \
    documentation/html/mavlink__msg__hil__state_8h_source.html \
    documentation/html/mavlink__msg__hil__state__quaternion_8h_source.html \
    documentation/html/mavlink__msg__home__position_8h_source.html \
    documentation/html/mavlink__msg__hwstatus_8h_source.html \
    documentation/html/mavlink__msg__isr__location_8h_source.html \
    documentation/html/mavlink__msg__landing__target_8h_source.html \
    documentation/html/mavlink__msg__led__control_8h_source.html \
    documentation/html/mavlink__msg__limits__status_8h_source.html \
    documentation/html/mavlink__msg__local__position__ned_8h_source.html \
    documentation/html/mavlink__msg__local__position__ned__cov_8h_source.html \
    documentation/html/mavlink__msg__local__position__ned__system__global__offset_8h_source.html \
    documentation/html/mavlink__msg__log__data_8h_source.html \
    documentation/html/mavlink__msg__log__entry_8h_source.html \
    documentation/html/mavlink__msg__log__erase_8h_source.html \
    documentation/html/mavlink__msg__log__request__data_8h_source.html \
    documentation/html/mavlink__msg__log__request__end_8h_source.html \
    documentation/html/mavlink__msg__log__request__list_8h_source.html \
    documentation/html/mavlink__msg__mag__cal__progress_8h_source.html \
    documentation/html/mavlink__msg__mag__cal__report_8h_source.html \
    documentation/html/mavlink__msg__manual__control_8h_source.html \
    documentation/html/mavlink__msg__manual__setpoint_8h_source.html \
    documentation/html/mavlink__msg__meminfo_8h_source.html \
    documentation/html/mavlink__msg__memory__vect_8h_source.html \
    documentation/html/mavlink__msg__message__interval_8h_source.html \
    documentation/html/mavlink__msg__mid__lvl__cmds_8h_source.html \
    documentation/html/mavlink__msg__mission__ack_8h_source.html \
    documentation/html/mavlink__msg__mission__clear__all_8h_source.html \
    documentation/html/mavlink__msg__mission__count_8h_source.html \
    documentation/html/mavlink__msg__mission__current_8h_source.html \
    documentation/html/mavlink__msg__mission__item_8h_source.html \
    documentation/html/mavlink__msg__mission__item__int_8h_source.html \
    documentation/html/mavlink__msg__mission__item__reached_8h_source.html \
    documentation/html/mavlink__msg__mission__request_8h_source.html \
    documentation/html/mavlink__msg__mission__request__int_8h_source.html \
    documentation/html/mavlink__msg__mission__request__list_8h_source.html \
    documentation/html/mavlink__msg__mission__request__partial__list_8h_source.html \
    documentation/html/mavlink__msg__mission__set__current_8h_source.html \
    documentation/html/mavlink__msg__mission__write__partial__list_8h_source.html \
    documentation/html/mavlink__msg__mount__configure_8h_source.html \
    documentation/html/mavlink__msg__mount__control_8h_source.html \
    documentation/html/mavlink__msg__mount__status_8h_source.html \
    documentation/html/mavlink__msg__named__value__float_8h_source.html \
    documentation/html/mavlink__msg__named__value__int_8h_source.html \
    documentation/html/mavlink__msg__nav__controller__output_8h_source.html \
    documentation/html/mavlink__msg__novatel__diag_8h_source.html \
    documentation/html/mavlink__msg__optical__flow_8h_source.html \
    documentation/html/mavlink__msg__optical__flow__rad_8h_source.html \
    documentation/html/mavlink__msg__param__map__rc_8h_source.html \
    documentation/html/mavlink__msg__param__request__list_8h_source.html \
    documentation/html/mavlink__msg__param__request__read_8h_source.html \
    documentation/html/mavlink__msg__param__set_8h_source.html \
    documentation/html/mavlink__msg__param__value_8h_source.html \
    documentation/html/mavlink__msg__pid__tuning_8h_source.html \
    documentation/html/mavlink__msg__ping_8h_source.html \
    documentation/html/mavlink__msg__play__tune_8h_source.html \
    documentation/html/mavlink__msg__position__target__global__int_8h_source.html \
    documentation/html/mavlink__msg__position__target__local__ned_8h_source.html \
    documentation/html/mavlink__msg__power__status_8h_source.html \
    documentation/html/mavlink__msg__ptz__status_8h_source.html \
    documentation/html/mavlink__msg__radio_8h_source.html \
    documentation/html/mavlink__msg__radio__status_8h_source.html \
    documentation/html/mavlink__msg__rally__fetch__point_8h_source.html \
    documentation/html/mavlink__msg__rally__point_8h_source.html \
    documentation/html/mavlink__msg__rangefinder_8h_source.html \
    documentation/html/mavlink__msg__raw__imu_8h_source.html \
    documentation/html/mavlink__msg__raw__pressure_8h_source.html \
    documentation/html/mavlink__msg__rc__channels_8h_source.html \
    documentation/html/mavlink__msg__rc__channels__override_8h_source.html \
    documentation/html/mavlink__msg__rc__channels__raw_8h_source.html \
    documentation/html/mavlink__msg__rc__channels__scaled_8h_source.html \
    documentation/html/mavlink__msg__remote__log__block__status_8h_source.html \
    documentation/html/mavlink__msg__remote__log__data__block_8h_source.html \
    documentation/html/mavlink__msg__request__data__stream_8h_source.html \
    documentation/html/mavlink__msg__resource__request_8h_source.html \
    documentation/html/mavlink__msg__rpm_8h_source.html \
    documentation/html/mavlink__msg__safety__allowed__area_8h_source.html \
    documentation/html/mavlink__msg__safety__set__allowed__area_8h_source.html \
    documentation/html/mavlink__msg__scaled__imu2_8h_source.html \
    documentation/html/mavlink__msg__scaled__imu3_8h_source.html \
    documentation/html/mavlink__msg__scaled__imu_8h_source.html \
    documentation/html/mavlink__msg__scaled__pressure2_8h_source.html \
    documentation/html/mavlink__msg__scaled__pressure3_8h_source.html \
    documentation/html/mavlink__msg__scaled__pressure_8h_source.html \
    documentation/html/mavlink__msg__sens__atmos_8h_source.html \
    documentation/html/mavlink__msg__sens__batmon_8h_source.html \
    documentation/html/mavlink__msg__sens__mppt_8h_source.html \
    documentation/html/mavlink__msg__sens__power_8h_source.html \
    documentation/html/mavlink__msg__sens__power__board_8h_source.html \
    documentation/html/mavlink__msg__sensor__bias_8h_source.html \
    documentation/html/mavlink__msg__sensor__diag_8h_source.html \
    documentation/html/mavlink__msg__sensor__offsets_8h_source.html \
    documentation/html/mavlink__msg__sensorpod__status_8h_source.html \
    documentation/html/mavlink__msg__serial__control_8h_source.html \
    documentation/html/mavlink__msg__serial__udb__extra__f13_8h_source.html \
    documentation/html/mavlink__msg__serial__udb__extra__f14_8h_source.html \
    documentation/html/mavlink__msg__serial__udb__extra__f15_8h_source.html \
    documentation/html/mavlink__msg__serial__udb__extra__f16_8h_source.html \
    documentation/html/mavlink__msg__serial__udb__extra__f2__a_8h_source.html \
    documentation/html/mavlink__msg__serial__udb__extra__f2__b_8h_source.html \
    documentation/html/mavlink__msg__serial__udb__extra__f4_8h_source.html \
    documentation/html/mavlink__msg__serial__udb__extra__f5_8h_source.html \
    documentation/html/mavlink__msg__serial__udb__extra__f6_8h_source.html \
    documentation/html/mavlink__msg__serial__udb__extra__f7_8h_source.html \
    documentation/html/mavlink__msg__serial__udb__extra__f8_8h_source.html \
    documentation/html/mavlink__msg__servo__output__raw_8h_source.html \
    documentation/html/mavlink__msg__set__actuator__control__target_8h_source.html \
    documentation/html/mavlink__msg__set__attitude__target_8h_source.html \
    documentation/html/mavlink__msg__set__gps__global__origin_8h_source.html \
    documentation/html/mavlink__msg__set__home__position_8h_source.html \
    documentation/html/mavlink__msg__set__mag__offsets_8h_source.html \
    documentation/html/mavlink__msg__set__mode_8h_source.html \
    documentation/html/mavlink__msg__set__position__target__global__int_8h_source.html \
    documentation/html/mavlink__msg__set__position__target__local__ned_8h_source.html \
    documentation/html/mavlink__msg__setup__signing_8h_source.html \
    documentation/html/mavlink__msg__sim__state_8h_source.html \
    documentation/html/mavlink__msg__simstate_8h_source.html \
    documentation/html/mavlink__msg__slugs__camera__order_8h_source.html \
    documentation/html/mavlink__msg__slugs__configuration__camera_8h_source.html \
    documentation/html/mavlink__msg__slugs__mobile__location_8h_source.html \
    documentation/html/mavlink__msg__slugs__navigation_8h_source.html \
    documentation/html/mavlink__msg__status__gps_8h_source.html \
    documentation/html/mavlink__msg__statustext_8h_source.html \
    documentation/html/mavlink__msg__sys__status_8h_source.html \
    documentation/html/mavlink__msg__system__time_8h_source.html \
    documentation/html/mavlink__msg__terrain__check_8h_source.html \
    documentation/html/mavlink__msg__terrain__data_8h_source.html \
    documentation/html/mavlink__msg__terrain__report_8h_source.html \
    documentation/html/mavlink__msg__terrain__request_8h_source.html \
    documentation/html/mavlink__msg__test__types_8h_source.html \
    documentation/html/mavlink__msg__timesync_8h_source.html \
    documentation/html/mavlink__msg__uav__status_8h_source.html \
    documentation/html/mavlink__msg__uavionix__adsb__out__cfg_8h_source.html \
    documentation/html/mavlink__msg__uavionix__adsb__out__dynamic_8h_source.html \
    documentation/html/mavlink__msg__uavionix__adsb__transceiver__health__report_8h_source.html \
    documentation/html/mavlink__msg__v2__extension_8h_source.html \
    documentation/html/mavlink__msg__vfr__hud_8h_source.html \
    documentation/html/mavlink__msg__vibration_8h_source.html \
    documentation/html/mavlink__msg__vicon__position__estimate_8h_source.html \
    documentation/html/mavlink__msg__vision__position__estimate_8h_source.html \
    documentation/html/mavlink__msg__vision__speed__estimate_8h_source.html \
    documentation/html/mavlink__msg__volt__sensor_8h_source.html \
    documentation/html/mavlink__msg__wind_8h_source.html \
    documentation/html/mavlink__msg__wind__cov_8h_source.html \
    documentation/html/mavlink__sha256_8h_source.html \
    documentation/html/mavlink__types_8h_source.html \
    documentation/html/md__r_e_a_d_m_e.html \
    documentation/html/minimal_2mavlink_8h.html \
    documentation/html/minimal_2mavlink_8h_source.html \
    documentation/html/minimal_2mavlink__msg__heartbeat_8h_source.html \
    documentation/html/minimal_2testsuite_8h.html \
    documentation/html/minimal_2testsuite_8h_source.html \
    documentation/html/minimal_2version_8h.html \
    documentation/html/minimal_2version_8h_source.html \
    documentation/html/minimal_8h.html \
    documentation/html/minimal_8h_source.html \
    documentation/html/pages.html \
    documentation/html/protocol_8h_source.html \
    documentation/html/slugs_2mavlink_8h.html \
    documentation/html/slugs_2mavlink_8h_source.html \
    documentation/html/slugs_2testsuite_8h.html \
    documentation/html/slugs_2testsuite_8h_source.html \
    documentation/html/slugs_2version_8h.html \
    documentation/html/slugs_2version_8h_source.html \
    documentation/html/slugs_8h.html \
    documentation/html/slugs_8h_source.html \
    documentation/html/struct____mavlink__field__info-members.html \
    documentation/html/struct____mavlink__field__info.html \
    documentation/html/struct____mavlink__message__info-members.html \
    documentation/html/struct____mavlink__message__info.html \
    documentation/html/struct____mavlink__msg__entry-members.html \
    documentation/html/struct____mavlink__msg__entry.html \
    documentation/html/struct____mavlink__signing-members.html \
    documentation/html/struct____mavlink__signing.html \
    documentation/html/struct____mavlink__signing__streams-members.html \
    documentation/html/struct____mavlink__signing__streams.html \
    documentation/html/struct____mavlink__signing__streams_1_1____mavlink__signing__stream-members.html \
    documentation/html/struct____mavlink__signing__streams_1_1____mavlink__signing__stream.html \
    documentation/html/struct____mavlink__status-members.html \
    documentation/html/struct____mavlink__status.html \
    documentation/html/structmavlink__sha256__ctx-members.html \
    documentation/html/structmavlink__sha256__ctx.html \
    documentation/html/test_2mavlink_8h.html \
    documentation/html/test_2mavlink_8h_source.html \
    documentation/html/test_2testsuite_8h.html \
    documentation/html/test_2testsuite_8h_source.html \
    documentation/html/test_2version_8h.html \
    documentation/html/test_2version_8h_source.html \
    documentation/html/test_8h.html \
    documentation/html/test_8h_source.html \
    documentation/html/u_avionix_2mavlink_8h.html \
    documentation/html/u_avionix_2mavlink_8h_source.html \
    documentation/html/u_avionix_2testsuite_8h.html \
    documentation/html/u_avionix_2testsuite_8h_source.html \
    documentation/html/u_avionix_2version_8h.html \
    documentation/html/u_avionix_2version_8h_source.html \
    documentation/html/u_avionix_8h.html \
    documentation/html/u_avionix_8h_source.html \
    documentation/html/uas__message_8hpp_source.html \
    documentation/html/union____mavlink__bitfield-members.html \
    documentation/html/union____mavlink__bitfield.html \
    documentation/html/_a_s_l_u_a_v_2mavlink_8h__incl.md5 \
    documentation/html/_a_s_l_u_a_v_2testsuite_8h__incl.md5 \
    documentation/html/_a_s_l_u_a_v_2version_8h__dep__incl.md5 \
    documentation/html/_a_s_l_u_a_v_8h__dep__incl.md5 \
    documentation/html/_a_s_l_u_a_v_8h__incl.md5 \
    documentation/html/ardupilotmega_2mavlink_8h__incl.md5 \
    documentation/html/ardupilotmega_2testsuite_8h__incl.md5 \
    documentation/html/ardupilotmega_2version_8h__dep__incl.md5 \
    documentation/html/ardupilotmega_8h__dep__incl.md5 \
    documentation/html/autoquad_2mavlink_8h__incl.md5 \
    documentation/html/autoquad_2testsuite_8h__incl.md5 \
    documentation/html/autoquad_2version_8h__dep__incl.md5 \
    documentation/html/autoquad_8h__dep__incl.md5 \
    documentation/html/autoquad_8h__incl.md5 \
    documentation/html/class_gcom_controller__coll__graph.md5 \
    documentation/html/class_gcom_controller__inherit__graph.md5 \
    documentation/html/common_2mavlink_8h__incl.md5 \
    documentation/html/common_2testsuite_8h__dep__incl.md5 \
    documentation/html/common_2version_8h__dep__incl.md5 \
    documentation/html/common_8h__dep__incl.md5 \
    documentation/html/dir_006c5adde132422c936285061c441fd6_dep.md5 \
    documentation/html/dir_2c8fe6371a64182b88962612e2d59269_dep.md5 \
    documentation/html/dir_547b956d4166df78c42c5049894a4888_dep.md5 \
    documentation/html/dir_83fc68f116d5d7b432bced6cbed0192e_dep.md5 \
    documentation/html/dir_c1a4da077515c6906d4cf31a479036ae_dep.md5 \
    documentation/html/dir_f2ea229d8e28506b03313778d82f530e_dep.md5 \
    documentation/html/graph_legend.md5 \
    documentation/html/inherit_graph_0.md5 \
    documentation/html/inherit_graph_1.md5 \
    documentation/html/inherit_graph_10.md5 \
    documentation/html/inherit_graph_2.md5 \
    documentation/html/inherit_graph_3.md5 \
    documentation/html/inherit_graph_4.md5 \
    documentation/html/inherit_graph_5.md5 \
    documentation/html/inherit_graph_6.md5 \
    documentation/html/inherit_graph_7.md5 \
    documentation/html/inherit_graph_8.md5 \
    documentation/html/inherit_graph_9.md5 \
    documentation/html/matrixpilot_2mavlink_8h__incl.md5 \
    documentation/html/matrixpilot_2testsuite_8h__incl.md5 \
    documentation/html/matrixpilot_2version_8h__dep__incl.md5 \
    documentation/html/matrixpilot_8h__dep__incl.md5 \
    documentation/html/matrixpilot_8h__incl.md5 \
    documentation/html/mavlink__conversions_8h__dep__incl.md5 \
    documentation/html/mavlink__conversions_8h__incl.md5 \
    documentation/html/mavlink__conversions_8h_a034c8265f27e81fa17cf4cf483b7ad8c_icgraph.md5 \
    documentation/html/mavlink__conversions_8h_a1acebd1df006ab806149f3bf9cc5544e_icgraph.md5 \
    documentation/html/mavlink__conversions_8h_a96913fc5846ae95f89c99423e4c0e6c1_cgraph.md5 \
    documentation/html/minimal_2mavlink_8h__incl.md5 \
    documentation/html/minimal_2version_8h__dep__incl.md5 \
    documentation/html/minimal_8h__dep__incl.md5 \
    documentation/html/minimal_8h__incl.md5 \
    documentation/html/slugs_2mavlink_8h__incl.md5 \
    documentation/html/slugs_2testsuite_8h__incl.md5 \
    documentation/html/slugs_2version_8h__dep__incl.md5 \
    documentation/html/slugs_8h__dep__incl.md5 \
    documentation/html/slugs_8h__incl.md5 \
    documentation/html/struct____mavlink__message__info__coll__graph.md5 \
    documentation/html/struct____mavlink__signing__coll__graph.md5 \
    documentation/html/struct____mavlink__signing__streams__coll__graph.md5 \
    documentation/html/struct____mavlink__status__coll__graph.md5 \
    documentation/html/test_2mavlink_8h__incl.md5 \
    documentation/html/test_2version_8h__dep__incl.md5 \
    documentation/html/test_8h__dep__incl.md5 \
    documentation/html/test_8h__incl.md5 \
    documentation/html/u_avionix_2mavlink_8h__incl.md5 \
    documentation/html/u_avionix_2testsuite_8h__dep__incl.md5 \
    documentation/html/u_avionix_2version_8h__dep__incl.md5 \
    documentation/html/u_avionix_8h__dep__incl.md5 \
    documentation/html/u_avionix_8h__incl.md5 \
    documentation/latex/_a_s_l_u_a_v_2mavlink_8h__incl.md5 \
    documentation/latex/_a_s_l_u_a_v_2testsuite_8h__incl.md5 \
    documentation/latex/_a_s_l_u_a_v_2version_8h__dep__incl.md5 \
    documentation/latex/_a_s_l_u_a_v_8h__dep__incl.md5 \
    documentation/latex/_a_s_l_u_a_v_8h__incl.md5 \
    documentation/latex/ardupilotmega_2mavlink_8h__incl.md5 \
    documentation/latex/ardupilotmega_2testsuite_8h__incl.md5 \
    documentation/latex/ardupilotmega_2version_8h__dep__incl.md5 \
    documentation/latex/ardupilotmega_8h__dep__incl.md5 \
    documentation/latex/autoquad_2mavlink_8h__incl.md5 \
    documentation/latex/autoquad_2testsuite_8h__incl.md5 \
    documentation/latex/autoquad_2version_8h__dep__incl.md5 \
    documentation/latex/autoquad_8h__dep__incl.md5 \
    documentation/latex/autoquad_8h__incl.md5 \
    documentation/latex/class_gcom_controller__coll__graph.md5 \
    documentation/latex/class_gcom_controller__inherit__graph.md5 \
    documentation/latex/common_2mavlink_8h__incl.md5 \
    documentation/latex/common_2testsuite_8h__dep__incl.md5 \
    documentation/latex/common_2version_8h__dep__incl.md5 \
    documentation/latex/common_8h__dep__incl.md5 \
    documentation/latex/dir_006c5adde132422c936285061c441fd6_dep.md5 \
    documentation/latex/dir_2c8fe6371a64182b88962612e2d59269_dep.md5 \
    documentation/latex/dir_547b956d4166df78c42c5049894a4888_dep.md5 \
    documentation/latex/dir_83fc68f116d5d7b432bced6cbed0192e_dep.md5 \
    documentation/latex/dir_c1a4da077515c6906d4cf31a479036ae_dep.md5 \
    documentation/latex/dir_f2ea229d8e28506b03313778d82f530e_dep.md5 \
    documentation/latex/make.bat \
    documentation/latex/matrixpilot_2mavlink_8h__incl.md5 \
    documentation/latex/matrixpilot_2testsuite_8h__incl.md5 \
    documentation/latex/matrixpilot_2version_8h__dep__incl.md5 \
    documentation/latex/matrixpilot_8h__dep__incl.md5 \
    documentation/latex/matrixpilot_8h__incl.md5 \
    documentation/latex/mavlink__conversions_8h__dep__incl.md5 \
    documentation/latex/mavlink__conversions_8h__incl.md5 \
    documentation/latex/mavlink__conversions_8h_a034c8265f27e81fa17cf4cf483b7ad8c_icgraph.md5 \
    documentation/latex/mavlink__conversions_8h_a1acebd1df006ab806149f3bf9cc5544e_icgraph.md5 \
    documentation/latex/mavlink__conversions_8h_a96913fc5846ae95f89c99423e4c0e6c1_cgraph.md5 \
    documentation/latex/minimal_2mavlink_8h__incl.md5 \
    documentation/latex/minimal_2version_8h__dep__incl.md5 \
    documentation/latex/minimal_8h__dep__incl.md5 \
    documentation/latex/minimal_8h__incl.md5 \
    documentation/latex/slugs_2mavlink_8h__incl.md5 \
    documentation/latex/slugs_2testsuite_8h__incl.md5 \
    documentation/latex/slugs_2version_8h__dep__incl.md5 \
    documentation/latex/slugs_8h__dep__incl.md5 \
    documentation/latex/slugs_8h__incl.md5 \
    documentation/latex/struct____mavlink__message__info__coll__graph.md5 \
    documentation/latex/struct____mavlink__signing__coll__graph.md5 \
    documentation/latex/struct____mavlink__signing__streams__coll__graph.md5 \
    documentation/latex/struct____mavlink__status__coll__graph.md5 \
    documentation/latex/test_2mavlink_8h__incl.md5 \
    documentation/latex/test_2version_8h__dep__incl.md5 \
    documentation/latex/test_8h__dep__incl.md5 \
    documentation/latex/test_8h__incl.md5 \
    documentation/latex/u_avionix_2mavlink_8h__incl.md5 \
    documentation/latex/u_avionix_2testsuite_8h__dep__incl.md5 \
    documentation/latex/u_avionix_2version_8h__dep__incl.md5 \
    documentation/latex/u_avionix_8h__dep__incl.md5 \
    documentation/latex/u_avionix_8h__incl.md5 \
    documentation/man/man3/__mavlink_bitfield.3 \
    documentation/man/man3/__mavlink_field_info.3 \
    documentation/man/man3/__mavlink_message_info.3 \
    documentation/man/man3/__mavlink_msg_entry.3 \
    documentation/man/man3/__mavlink_signing.3 \
    documentation/man/man3/__mavlink_signing_streams.3 \
    documentation/man/man3/__mavlink_signing_streams___mavlink_signing_stream.3 \
    documentation/man/man3/__mavlink_status.3 \
    documentation/man/man3/C__Users_Zeyad_OneDrive_Projects_UAS_gcom_Mavlink_.3 \
    documentation/man/man3/C__Users_Zeyad_OneDrive_Projects_UAS_gcom_Mavlink_ardupilotmega_.3 \
    documentation/man/man3/C__Users_Zeyad_OneDrive_Projects_UAS_gcom_Mavlink_ASLUAV_.3 \
    documentation/man/man3/C__Users_Zeyad_OneDrive_Projects_UAS_gcom_Mavlink_autoquad_.3 \
    documentation/man/man3/C__Users_Zeyad_OneDrive_Projects_UAS_gcom_Mavlink_common_.3 \
    documentation/man/man3/C__Users_Zeyad_OneDrive_Projects_UAS_gcom_Mavlink_matrixpilot_.3 \
    documentation/man/man3/C__Users_Zeyad_OneDrive_Projects_UAS_gcom_Mavlink_minimal_.3 \
    documentation/man/man3/C__Users_Zeyad_OneDrive_Projects_UAS_gcom_Mavlink_slugs_.3 \
    documentation/man/man3/C__Users_Zeyad_OneDrive_Projects_UAS_gcom_Mavlink_test_.3 \
    documentation/man/man3/C__Users_Zeyad_OneDrive_Projects_UAS_gcom_Mavlink_uAvionix_.3 \
    documentation/man/man3/C__Users_Zeyad_OneDrive_Projects_UAS_gcom_utility_.3 \
    documentation/man/man3/GcomController.3 \
    documentation/man/man3/mavlink_sha256_ctx.3 \
    documentation/man/man3/md__r_e_a_d_m_e.3 \
    documentation/man/man3/testsuite.h.3 \
    documentation/man/man3/UASMessage_UASMessage.3 \
    documentation/man/man3/version.h.3 \
    documentation/Doxyfile \
    LICENSE \
    documentation/html/_a_s_l_u_a_v_2mavlink_8h__incl.dot \
    documentation/html/_a_s_l_u_a_v_2testsuite_8h__incl.dot \
    documentation/html/_a_s_l_u_a_v_2version_8h__dep__incl.dot \
    documentation/html/_a_s_l_u_a_v_8h__dep__incl.dot \
    documentation/html/_a_s_l_u_a_v_8h__incl.dot \
    documentation/html/ardupilotmega_2mavlink_8h__incl.dot \
    documentation/html/ardupilotmega_2testsuite_8h__incl.dot \
    documentation/html/ardupilotmega_2version_8h__dep__incl.dot \
    documentation/html/ardupilotmega_8h__dep__incl.dot \
    documentation/html/autoquad_2mavlink_8h__incl.dot \
    documentation/html/autoquad_2testsuite_8h__incl.dot \
    documentation/html/autoquad_2version_8h__dep__incl.dot \
    documentation/html/autoquad_8h__dep__incl.dot \
    documentation/html/autoquad_8h__incl.dot \
    documentation/html/class_gcom_controller__coll__graph.dot \
    documentation/html/class_gcom_controller__inherit__graph.dot \
    documentation/html/common_2mavlink_8h__incl.dot \
    documentation/html/common_2testsuite_8h__dep__incl.dot \
    documentation/html/common_2version_8h__dep__incl.dot \
    documentation/html/common_8h__dep__incl.dot \
    documentation/html/dir_006c5adde132422c936285061c441fd6_dep.dot \
    documentation/html/dir_2c8fe6371a64182b88962612e2d59269_dep.dot \
    documentation/html/dir_547b956d4166df78c42c5049894a4888_dep.dot \
    documentation/html/dir_83fc68f116d5d7b432bced6cbed0192e_dep.dot \
    documentation/html/dir_c1a4da077515c6906d4cf31a479036ae_dep.dot \
    documentation/html/dir_f2ea229d8e28506b03313778d82f530e_dep.dot \
    documentation/html/graph_legend.dot \
    documentation/html/inherit_graph_0.dot \
    documentation/html/inherit_graph_1.dot \
    documentation/html/inherit_graph_10.dot \
    documentation/html/inherit_graph_2.dot \
    documentation/html/inherit_graph_3.dot \
    documentation/html/inherit_graph_4.dot \
    documentation/html/inherit_graph_5.dot \
    documentation/html/inherit_graph_6.dot \
    documentation/html/inherit_graph_7.dot \
    documentation/html/inherit_graph_8.dot \
    documentation/html/inherit_graph_9.dot \
    documentation/html/matrixpilot_2mavlink_8h__incl.dot \
    documentation/html/matrixpilot_2testsuite_8h__incl.dot \
    documentation/html/matrixpilot_2version_8h__dep__incl.dot \
    documentation/html/matrixpilot_8h__dep__incl.dot \
    documentation/html/matrixpilot_8h__incl.dot \
    documentation/html/mavlink__conversions_8h__dep__incl.dot \
    documentation/html/mavlink__conversions_8h__incl.dot \
    documentation/html/mavlink__conversions_8h_a034c8265f27e81fa17cf4cf483b7ad8c_icgraph.dot \
    documentation/html/mavlink__conversions_8h_a1acebd1df006ab806149f3bf9cc5544e_icgraph.dot \
    documentation/html/mavlink__conversions_8h_a96913fc5846ae95f89c99423e4c0e6c1_cgraph.dot \
    documentation/html/minimal_2mavlink_8h__incl.dot \
    documentation/html/minimal_2version_8h__dep__incl.dot \
    documentation/html/minimal_8h__dep__incl.dot \
    documentation/html/minimal_8h__incl.dot \
    documentation/html/slugs_2mavlink_8h__incl.dot \
    documentation/html/slugs_2testsuite_8h__incl.dot \
    documentation/html/slugs_2version_8h__dep__incl.dot \
    documentation/html/slugs_8h__dep__incl.dot \
    documentation/html/slugs_8h__incl.dot \
    documentation/html/struct____mavlink__message__info__coll__graph.dot \
    documentation/html/struct____mavlink__signing__coll__graph.dot \
    documentation/html/struct____mavlink__signing__streams__coll__graph.dot \
    documentation/html/struct____mavlink__status__coll__graph.dot \
    documentation/html/test_2mavlink_8h__incl.dot \
    documentation/html/test_2version_8h__dep__incl.dot \
    documentation/html/test_8h__dep__incl.dot \
    documentation/html/test_8h__incl.dot \
    documentation/html/u_avionix_2mavlink_8h__incl.dot \
    documentation/html/u_avionix_2testsuite_8h__dep__incl.dot \
    documentation/html/u_avionix_2version_8h__dep__incl.dot \
    documentation/html/u_avionix_8h__dep__incl.dot \
    documentation/html/u_avionix_8h__incl.dot \
    documentation/latex/_a_s_l_u_a_v_2mavlink_8h__incl.dot \
    documentation/latex/_a_s_l_u_a_v_2testsuite_8h__incl.dot \
    documentation/latex/_a_s_l_u_a_v_2version_8h__dep__incl.dot \
    documentation/latex/_a_s_l_u_a_v_8h__dep__incl.dot \
    documentation/latex/_a_s_l_u_a_v_8h__incl.dot \
    documentation/latex/ardupilotmega_2mavlink_8h__incl.dot \
    documentation/latex/ardupilotmega_2testsuite_8h__incl.dot \
    documentation/latex/ardupilotmega_2version_8h__dep__incl.dot \
    documentation/latex/ardupilotmega_8h__dep__incl.dot \
    documentation/latex/autoquad_2mavlink_8h__incl.dot \
    documentation/latex/autoquad_2testsuite_8h__incl.dot \
    documentation/latex/autoquad_2version_8h__dep__incl.dot \
    documentation/latex/autoquad_8h__dep__incl.dot \
    documentation/latex/autoquad_8h__incl.dot \
    documentation/latex/class_gcom_controller__coll__graph.dot \
    documentation/latex/class_gcom_controller__inherit__graph.dot \
    documentation/latex/common_2mavlink_8h__incl.dot \
    documentation/latex/common_2testsuite_8h__dep__incl.dot \
    documentation/latex/common_2version_8h__dep__incl.dot \
    documentation/latex/common_8h__dep__incl.dot \
    documentation/latex/dir_006c5adde132422c936285061c441fd6_dep.dot \
    documentation/latex/dir_2c8fe6371a64182b88962612e2d59269_dep.dot \
    documentation/latex/dir_547b956d4166df78c42c5049894a4888_dep.dot \
    documentation/latex/dir_83fc68f116d5d7b432bced6cbed0192e_dep.dot \
    documentation/latex/dir_c1a4da077515c6906d4cf31a479036ae_dep.dot \
    documentation/latex/dir_f2ea229d8e28506b03313778d82f530e_dep.dot \
    documentation/latex/matrixpilot_2mavlink_8h__incl.dot \
    documentation/latex/matrixpilot_2testsuite_8h__incl.dot \
    documentation/latex/matrixpilot_2version_8h__dep__incl.dot \
    documentation/latex/matrixpilot_8h__dep__incl.dot \
    documentation/latex/matrixpilot_8h__incl.dot \
    documentation/latex/mavlink__conversions_8h__dep__incl.dot \
    documentation/latex/mavlink__conversions_8h__incl.dot \
    documentation/latex/mavlink__conversions_8h_a034c8265f27e81fa17cf4cf483b7ad8c_icgraph.dot \
    documentation/latex/mavlink__conversions_8h_a1acebd1df006ab806149f3bf9cc5544e_icgraph.dot \
    documentation/latex/mavlink__conversions_8h_a96913fc5846ae95f89c99423e4c0e6c1_cgraph.dot \
    documentation/latex/minimal_2mavlink_8h__incl.dot \
    documentation/latex/minimal_2version_8h__dep__incl.dot \
    documentation/latex/minimal_8h__dep__incl.dot \
    documentation/latex/minimal_8h__incl.dot \
    documentation/latex/slugs_2mavlink_8h__incl.dot \
    documentation/latex/slugs_2testsuite_8h__incl.dot \
    documentation/latex/slugs_2version_8h__dep__incl.dot \
    documentation/latex/slugs_8h__dep__incl.dot \
    documentation/latex/slugs_8h__incl.dot \
    documentation/latex/struct____mavlink__message__info__coll__graph.dot \
    documentation/latex/struct____mavlink__signing__coll__graph.dot \
    documentation/latex/struct____mavlink__signing__streams__coll__graph.dot \
    documentation/latex/struct____mavlink__status__coll__graph.dot \
    documentation/latex/test_2mavlink_8h__incl.dot \
    documentation/latex/test_2version_8h__dep__incl.dot \
    documentation/latex/test_8h__dep__incl.dot \
    documentation/latex/test_8h__incl.dot \
    documentation/latex/u_avionix_2mavlink_8h__incl.dot \
    documentation/latex/u_avionix_2testsuite_8h__dep__incl.dot \
    documentation/latex/u_avionix_2version_8h__dep__incl.dot \
    documentation/latex/u_avionix_8h__dep__incl.dot \
    documentation/latex/u_avionix_8h__incl.dot \
    README.md \
    documentation/latex/_a_s_l_u_a_v_2mavlink_8h.tex \
    documentation/latex/_a_s_l_u_a_v_2testsuite_8h.tex \
    documentation/latex/_a_s_l_u_a_v_2version_8h.tex \
    documentation/latex/_a_s_l_u_a_v_8h.tex \
    documentation/latex/annotated.tex \
    documentation/latex/ardupilotmega_2mavlink_8h.tex \
    documentation/latex/ardupilotmega_2testsuite_8h.tex \
    documentation/latex/ardupilotmega_2version_8h.tex \
    documentation/latex/ardupilotmega_8h.tex \
    documentation/latex/autoquad_2mavlink_8h.tex \
    documentation/latex/autoquad_2testsuite_8h.tex \
    documentation/latex/autoquad_2version_8h.tex \
    documentation/latex/autoquad_8h.tex \
    documentation/latex/class_gcom_controller.tex \
    documentation/latex/class_u_a_s_message_1_1_u_a_s_message.tex \
    documentation/latex/common_2mavlink_8h.tex \
    documentation/latex/common_2testsuite_8h.tex \
    documentation/latex/common_2version_8h.tex \
    documentation/latex/common_8h.tex \
    documentation/latex/dir_006c5adde132422c936285061c441fd6.tex \
    documentation/latex/dir_0da6529a5eada8fcebcd8e4c2a5a9bb4.tex \
    documentation/latex/dir_2c8fe6371a64182b88962612e2d59269.tex \
    documentation/latex/dir_4c057851c48f94592cfeafad14b1565d.tex \
    documentation/latex/dir_547b956d4166df78c42c5049894a4888.tex \
    documentation/latex/dir_6439a1e482aa07981dd6ab8c460c3ef8.tex \
    documentation/latex/dir_64e73385a8b7738563c26ce10415b58d.tex \
    documentation/latex/dir_83fc68f116d5d7b432bced6cbed0192e.tex \
    documentation/latex/dir_bcd2bb1aa02f875b186a4aa98bbb035f.tex \
    documentation/latex/dir_c1a4da077515c6906d4cf31a479036ae.tex \
    documentation/latex/dir_f2ea229d8e28506b03313778d82f530e.tex \
    documentation/latex/doxygen.sty \
    documentation/latex/files.tex \
    documentation/latex/hierarchy.tex \
    documentation/latex/matrixpilot_2mavlink_8h.tex \
    documentation/latex/matrixpilot_2testsuite_8h.tex \
    documentation/latex/matrixpilot_2version_8h.tex \
    documentation/latex/matrixpilot_8h.tex \
    documentation/latex/mavlink__conversions_8h.tex \
    documentation/latex/md__r_e_a_d_m_e.tex \
    documentation/latex/minimal_2mavlink_8h.tex \
    documentation/latex/minimal_2testsuite_8h.tex \
    documentation/latex/minimal_2version_8h.tex \
    documentation/latex/minimal_8h.tex \
    documentation/latex/refman.tex \
    documentation/latex/slugs_2mavlink_8h.tex \
    documentation/latex/slugs_2testsuite_8h.tex \
    documentation/latex/slugs_2version_8h.tex \
    documentation/latex/slugs_8h.tex \
    documentation/latex/struct____mavlink__field__info.tex \
    documentation/latex/struct____mavlink__message__info.tex \
    documentation/latex/struct____mavlink__msg__entry.tex \
    documentation/latex/struct____mavlink__signing.tex \
    documentation/latex/struct____mavlink__signing__streams.tex \
    documentation/latex/struct____mavlink__signing__streams_1_1____mavlink__signing__stream.tex \
    documentation/latex/struct____mavlink__status.tex \
    documentation/latex/structmavlink__sha256__ctx.tex \
    documentation/latex/test_2mavlink_8h.tex \
    documentation/latex/test_2testsuite_8h.tex \
    documentation/latex/test_2version_8h.tex \
    documentation/latex/test_8h.tex \
    documentation/latex/u_avionix_2mavlink_8h.tex \
    documentation/latex/u_avionix_2testsuite_8h.tex \
    documentation/latex/u_avionix_2version_8h.tex \
    documentation/latex/u_avionix_8h.tex \
    documentation/latex/union____mavlink__bitfield.tex
