.TH "__mavlink_signing_streams" 3 "Mon Oct 10 2016" "Version 1.0" "G-COM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__mavlink_signing_streams \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB__mavlink_signing_stream\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBnum_signing_streams\fP"
.br
.ti -1c
.RI "struct \fB__mavlink_signing_streams::__mavlink_signing_stream\fP \fBstream\fP [MAVLINK_MAX_SIGNING_STREAMS]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 257 of file mavlink_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for G-COM from the source code\&.
