.TH "__mavlink_signing" 3 "Mon Oct 10 2016" "Version 1.0" "G-COM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__mavlink_signing \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBflags\fP"
.br
.RI "MAVLINK_SIGNING_FLAG_*\&. "
.ti -1c
.RI "uint8_t \fBlink_id\fP"
.br
.ti -1c
.RI "uint64_t \fBtimestamp\fP"
.br
.ti -1c
.RI "uint8_t \fBsecret_key\fP [32]"
.br
.ti -1c
.RI "mavlink_accept_unsigned_t \fBaccept_unsigned_callback\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 242 of file mavlink_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for G-COM from the source code\&.
