.TH "__mavlink_field_info" 3 "Mon Oct 10 2016" "Version 1.0" "G-COM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__mavlink_field_info \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char * \fBprint_format\fP"
.br
.ti -1c
.RI "mavlink_message_type_t \fBtype\fP"
.br
.ti -1c
.RI "unsigned int \fBarray_length\fP"
.br
.ti -1c
.RI "unsigned int \fBwire_offset\fP"
.br
.ti -1c
.RI "unsigned int \fBstructure_offset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 135 of file mavlink_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for G-COM from the source code\&.
