.TH "__mavlink_message_info" 3 "Mon Oct 10 2016" "Version 1.0" "G-COM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__mavlink_message_info \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBmsgid\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "unsigned \fBnum_fields\fP"
.br
.ti -1c
.RI "\fBmavlink_field_info_t\fP \fBfields\fP [MAVLINK_MAX_FIELDS]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 146 of file mavlink_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for G-COM from the source code\&.
