.TH "GcomController" 3 "Mon Oct 10 2016" "Version 1.0" "G-COM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GcomController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGcomController\fP (QWidget *parent=0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file gcomcontroller\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for G-COM from the source code\&.
