.TH "Mavlink/uAvionix/mavlink.h" 3 "Mon Oct 10 2016" "Version 1.0" "G-COM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mavlink/uAvionix/mavlink.h \- MAVLink comm protocol built from uAvionix\&.xml\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'version\&.h'\fP
.br
\fC#include 'uAvionix\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAVLINK_STX\fP   253"
.br
.ti -1c
.RI "#define \fBMAVLINK_ENDIAN\fP   MAVLINK_LITTLE_ENDIAN"
.br
.ti -1c
.RI "#define \fBMAVLINK_ALIGNED_FIELDS\fP   1"
.br
.ti -1c
.RI "#define \fBMAVLINK_CRC_EXTRA\fP   1"
.br
.ti -1c
.RI "#define \fBMAVLINK_COMMAND_24BIT\fP   1"
.br
.in -1c
.SH "Detailed Description"
.PP 
MAVLink comm protocol built from uAvionix\&.xml\&. 


.PP
\fBSee also:\fP
.RS 4
http://mavlink.org 
.RE
.PP

.PP
Definition in file \fBmavlink\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for G-COM from the source code\&.
