.TH "mavlink_sha256_ctx" 3 "Mon Oct 10 2016" "Version 1.0" "G-COM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mavlink_sha256_ctx \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBsz\fP [2]"
.br
.ti -1c
.RI "uint32_t \fBcounter\fP [8]"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   unsigned char \fBsave_bytes\fP [64]"
.br
.ti -1c
.RI "   uint32_t \fBsave_u32\fP [16]"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file mavlink_sha256\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for G-COM from the source code\&.
