.TH "Mavlink/uAvionix/version.h" 3 "Mon Oct 10 2016" "Version 1.0" "G-COM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mavlink/uAvionix/version.h \- MAVLink comm protocol built from uAvionix\&.xml\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAVLINK_BUILD_DATE\fP   'Mon Sep 19 2016'"
.br
.ti -1c
.RI "#define \fBMAVLINK_WIRE_PROTOCOL_VERSION\fP   '2\&.0'"
.br
.ti -1c
.RI "#define \fBMAVLINK_MAX_DIALECT_PAYLOAD_SIZE\fP   255"
.br
.in -1c
.SH "Detailed Description"
.PP 
MAVLink comm protocol built from uAvionix\&.xml\&. 


.PP
\fBSee also:\fP
.RS 4
http://mavlink.org 
.RE
.PP

.PP
Definition in file \fBversion\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for G-COM from the source code\&.
